name: GitHub Actions cas1 Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: workflow_dispatch
env:
  VARIABLE_2: variable workflow
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Variable 1 entorn-> ${{ vars.VARIABLE_1 }}."
      - run: echo "Variable 2 entorn-> ${{ env.VARIABLE_2 }}."
      - run: echo "Variable 2 entorn-> ${{ env.VARIABLE_2 }}."
        env:
           VARIABLE_2: variable tasque

  Explore-GitHub-Actions1:
      runs-on: ubuntu-latest
      needs: Explore-GitHub-Actions
      steps:
        - uses: actions/checkout@v4
        - name: upload output file
          uses: actions/upload-artifact@v4
          with:
            name: output-log-file
            path: text.txt
            
  Explore-GitHub-Actions2:
      runs-on: ubuntu-latest
      needs: Explore-GitHub-Actions1
      steps:
        - name: Download a single artifact
          uses: actions/download-artifact@v4
          with:
            name: output-log-file
        - run: cat text.txt
