name: GitHub Actions cas1 Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [workflow_dispatch]
env:
  VARIABLE_2: variable workflow
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Variable 1 entorn-> ${{ vars.VARIABLE_1 }}."
      - run: echo "Variable 2 entorn-> ${{ env.VARIABLE_2 }}."
      - run: echo "Variable 2 entorn-> ${{ env.VARIABLE_2 }}."
        env:
           VARIABLE_2: variable tasque
