name: GitHub Actions cas1 Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Variable 1 entorn" ${{ vars.VARIABLE_1 }}."